CREATE TABLE DIRECTOR
(Director_ID INT AUTO_INCREMENT,
First_Name VARCHAR(50) NOT NULL,
Last_Name VARCHAR(50) NOT NULL,
CONSTRAINT PK_DIRECTOR PRIMARY KEY(Director_ID));

CREATE TABLE SHOW_TYPE
(Show_Type_ID INT AUTO_INCREMENT,
Show_Type VARCHAR(50) NOT NULL,
CONSTRAINT PK_SHOW_TYPE PRIMARY KEY(Show_Type_ID));

CREATE TABLE MATURITY_RATING
(Rating_ID INT AUTO_INCREMENT,
Rating VARCHAR(10) NOT NULL,
CONSTRAINT PK_MATURITY_RATING PRIMARY KEY(Rating_ID));

CREATE TABLE COUNTRY
(Country_ID INT AUTO_INCREMENT,
Country VARCHAR(50) NOT NULL,
CONSTRAINT PK_COUNTRY PRIMARY KEY(Country_ID));

CREATE TABLE ACTOR
(Actor_ID INT AUTO_INCREMENT,
First_Name Varchar(50) NOT NULL,
Last_Name Varchar(50) NOT NULL,
CONSTRAINT PK_ACTOR PRIMARY KEY(Actor_ID));

CREATE TABLE GENRE
(Genre_ID INT AUTO_INCREMENT,
Genre VARCHAR(25) NOT NULL,
CONSTRAINT PK_GENRE PRIMARY KEY(Genre_ID));

CREATE TABLE SHOW_DETAILS
(Show_ID INT AUTO_INCREMENT,
Title VARCHAR(255) NOT NULL,
Show_Type_ID INT,
Date_Added DATE NOT NULL,
Release_Year YEAR NOT NULL, 
Duration_Value INT, 
Duration_Unit VARCHAR(10),
`Description` TEXT,
Rating_ID INT,
Last_Updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT PK_SHOW_DETAILS PRIMARY KEY(Show_ID));

CREATE TABLE SHOW_DIRECTOR_INT
(Show_ID INT,
Director_ID INT,
CONSTRAINT PK_SHOW_DIRECTOR_INT PRIMARY KEY(Show_ID, Director_ID));

CREATE TABLE SHOW_COUNTRY_INT
(Show_ID INT,
Country_ID INT,
CONSTRAINT PK_SHOW_COUNTRY_INT PRIMARY KEY(Show_ID, Country_ID));

CREATE TABLE SHOW_ACTOR_INT
(Show_ID INT,
Actor_ID INT,
CONSTRAINT PK_SHOW_ACTOR_INT PRIMARY KEY(Show_ID, Actor_ID));

CREATE TABLE SHOW_GENRE_INT
(Show_ID INT,
Genre_ID INT,
CONSTRAINT PK_SHOW_GENRE_INT PRIMARY KEY(Show_ID, Genre_ID));

ALTER TABLE SHOW_DIRECTOR_INT
ADD CONSTRAINT FK_SHOW_DIRECTOR_INT_SHOW_ID FOREIGN KEY(Show_ID) REFERENCES SHOW_DETAILS(Show_ID),
ADD CONSTRAINT FK_SHOW_DIRECTOR_INT_DIRECTOR_ID FOREIGN KEY(Director_ID) REFERENCES DIRECTOR(Director_ID);

ALTER TABLE SHOW_COUNTRY_INT
ADD CONSTRAINT FK_SHOW_COUNTRY_INT_SHOW_ID FOREIGN KEY(Show_ID) REFERENCES SHOW_DETAILS(Show_ID),
ADD CONSTRAINT FK_SHOW_COUNTRY_INT_COUNTRY_ID FOREIGN KEY(Country_ID) REFERENCES COUNTRY(Country_ID);

ALTER TABLE SHOW_ACTOR_INT
ADD CONSTRAINT FK_SHOW_ACTOR_INT_SHOW_ID FOREIGN KEY(Show_ID) REFERENCES SHOW_DETAILS(Show_ID),
ADD CONSTRAINT FK_SHOW_ACTOR_INT_ACTOR_ID FOREIGN KEY(Actor_ID) REFERENCES ACTOR(Actor_ID);

ALTER TABLE SHOW_GENRE_INT
ADD CONSTRAINT FK_SHOW_GENRE_INT_SHOW_ID FOREIGN KEY(Show_ID) REFERENCES SHOW_DETAILS(Show_ID),
ADD CONSTRAINT FK_SHOW_GENRE_INT_GENRE_ID FOREIGN KEY(Genre_ID) REFERENCES GENRE(Genre_ID);

ALTER TABLE SHOW_DETAILS
ADD CONSTRAINT FK_SHOW_DETAILS_SHOW_TYPE_ID FOREIGN KEY(Show_Type_ID) REFERENCES SHOW_TYPE(Show_Type_ID),
ADD CONSTRAINT FK_SHOW_DETAILS_RATING_ID FOREIGN KEY(Rating_ID) REFERENCES MATURITY_RATING(Rating_ID);


ALTER TABLE SHOW_TYPE
MODIFY Show_Type VARCHAR(50) NOT NULL;

ALTER TABLE MATURITY_RATING
MODIFY Rating VARCHAR(10) NOT NULL;

ALTER TABLE SHOW_DETAILS
MODIFY Duration_Unit VARCHAR(10);

ALTER TABLE GENRE ADD UNIQUE(Genre);
ALTER TABLE COUNTRY ADD UNIQUE(Country);
ALTER TABLE DIRECTOR ADD UNIQUE(First_Name, Last_Name);
ALTER TABLE ACTOR ADD UNIQUE(First_Name, Last_Name);
ALTER TABLE SHOW_TYPE ADD UNIQUE(Show_Type);
ALTER TABLE MATURITY_RATING ADD UNIQUE(Rating);
ALTER TABLE SHOW_GENRE_INT ADD UNIQUE(Show_ID, Genre_ID);
ALTER TABLE SHOW_DIRECTOR_INT ADD UNIQUE(Show_ID, Director_ID);
ALTER TABLE SHOW_ACTOR_INT ADD UNIQUE(Show_ID, Actor_ID);
ALTER TABLE SHOW_COUNTRY_INT ADD UNIQUE(Show_ID, Country_ID);

CREATE VIEW vw_ALL AS
SELECT
sd.Show_ID AS show_id,
st.Show_Type AS `type`,
sd.Title AS title,
GROUP_CONCAT(DISTINCT CONCAT(d.First_Name, ' ', d.Last_Name)) AS director,
GROUP_CONCAT(DISTINCT CONCAT(a.First_Name, ' ', a.Last_Name)) AS cast,
GROUP_CONCAT(DISTINCT c.Country) AS country,
sd.Date_Added AS date_added,
sd.Release_Year AS release_year,
m.Rating AS rating,
CONCAT(sd.Duration_Value, ' ', sd.Duration_Unit) AS duration,
GROUP_CONCAT(DISTINCT g.Genre)  AS listed_in,
sd.`Description` AS `description`
FROM SHOW_DETAILS sd JOIN SHOW_TYPE st ON sd.Show_Type_ID = st.Show_Type_ID
JOIN MATURITY_RATING m ON m.Rating_ID = sd.Rating_ID 
JOIN SHOW_GENRE_INT sgi ON sgi.Show_ID = sd.Show_ID 
JOIN GENRE g ON sgi.Genre_ID = g.Genre_ID
JOIN SHOW_DIRECTOR_INT sdi ON sdi.Show_ID = sd.Show_ID
JOIN DIRECTOR d ON d.Director_ID = sdi.Director_ID
JOIN SHOW_COUNTRY_INT sci ON sci.Show_ID = sd.Show_ID 
JOIN COUNTRY c ON c.Country_ID = sci.Country_ID
JOIN SHOW_ACTOR_INT sai ON sai.Show_ID = sd.Show_ID 
JOIN ACTOR a ON a.Actor_ID = sai.Actor_ID
GROUP BY sd.Show_ID;
